spring:
  application:
    name: catsapi
  datasource:
    url: jdbc:h2:mem:cats
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: DETECT
  main:
    banner-mode: off

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enabled: true
    tags:
      enabled: true

logging:
  pattern:
    console: '%clr(%d{HH:mm:ss}){yellow} %clr([%-5.5thread]){magenta} %highlight(%-5.5level) %clr(%-30.30logger{10}){cyan} - %msg%n'
  level:
    root: INFO
    org.springframework: WARN
    com.priscila.catsapi: DEBUG