spring:
  application:
    name: catsapi
  datasource:
    url: jdbc:h2:mem:cats
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: DETECT
  main:
    banner-mode: off

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# CORS configuration
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:3000" 
    - "http://127.0.0.1:5173"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enabled: true
    tags:
      enabled: true

logging:
  pattern:
    console: '%clr(%d{HH:mm:ss}){yellow} %clr([%-5.5thread]){magenta} %highlight(%-5.5level) %clr(%-30.30logger{10}){cyan} - %msg%n'
  level:
    root: INFO
    org.springframework: WARN
    com.priscila.catsapi: DEBUG