spring:
  application:
    name: catsapi
  datasource:
    url: jdbc:h2:mem:cats
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  management:
    server:
      port: 8080

    endpoints:
      web:
        exposure:
          include: "prometheus, health, info"
    metrics:
      export:
        prometheus:
          enabled: true
  spring:
    application:
      name: catsapi
    output:
      ansi:
        enabled: DETECT
    main:
      banner-mode: off