#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "catsapi"
    metrics_path: "/actuator/promethgit checkout maineus"
    static_configs:
      - targets: ["host.docker.internal:8080"]